<a href="https://colab.research.google.com/github/brianisinga/jupyterWorkflow/blob/main/tf_trained_model%20with%20keras%20API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.15.0


**loading a dataset**

In [5]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/ 255.0, x_test /255.0

11490434/11490434 [==============================] - 1s 0us/step


**build a machine learning model**

In [7]:
#build a tf.keras.Sequential model
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation = "relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [10]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.22667192,  0.04126984, -0.20580553,  0.0593311 ,  0.5056819 ,
         0.21814534,  0.38510597,  0.0015454 ,  0.14911684, -0.643508  ]],
      dtype=float32)

**tf.softmax** *function converts these logits to probabilities for each class*

In [11]:
tf.nn.softmax(predictions).numpy()

array([[0.07399207, 0.09672768, 0.07555223, 0.09849057, 0.15390132,
        0.1154428 , 0.13641964, 0.09296055, 0.10774276, 0.04877031]],
      dtype=float32)

*define a loss function for training using* **losses.SparseCategoricalCrossentropy**

In [12]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [15]:
-tf.math.log(1/10).numpy()

2.3025851

In [19]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics = ['accuracy'])

**Train aand evaluate your model**

In [20]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2948 - accuracy: 0.9142
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1466 - accuracy: 0.9562
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1087 - accuracy: 0.9669
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0875 - accuracy: 0.9730
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0778 - accuracy: 0.9747


In [21]:
model.evaluate(x_test, y_test, verbose = 2)

313/313 - 1s - loss: 0.0825 - accuracy: 0.9747 - 691ms/epoch - 2ms/step


[0.08248909562826157, 0.9746999740600586]

**If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:**

In [22]:
probability_model = tf.keras.Sequential([model,tf.keras.layers.Softmax()])

In [23]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.7107332e-08, 1.1540234e-09, 4.1842304e-06, 3.4792125e-04,
        1.2130416e-10, 3.8889576e-07, 3.9359317e-15, 9.9963760e-01,
        3.3643819e-06, 6.4449091e-06],
       [6.8253501e-09, 3.8181082e-05, 9.9939334e-01, 5.6717760e-04,
        8.3891363e-15, 4.5821491e-07, 2.2686375e-07, 3.6025306e-12,
        6.4554661e-07, 3.6710844e-15],
       [2.2201126e-08, 9.9762088e-01, 2.5430744e-04, 9.9388535e-06,
        1.2387684e-05, 9.1230277e-07, 1.7864621e-05, 1.7630175e-03,
        3.2030875e-04, 2.7827377e-07],
       [9.9967861e-01, 1.0531469e-09, 7.5521100e-05, 6.2947635e-07,
        3.4213630e-05, 2.0043952e-05, 1.3094502e-04, 3.3686440e-05,
        9.8464220e-08, 2.6231874e-05],
       [3.6712177e-07, 1.5474741e-11, 9.6268863e-08, 7.7317734e-09,
        9.9813193e-01, 5.7689590e-07, 8.1002946e-07, 6.8573613e-06,
        7.4344325e-07, 1.8585809e-03]], dtype=float32)>